//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace License.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("License.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия bimteam.org.
        /// </summary>
        public static string BTLicense {
            get {
                return ResourceManager.GetString("BTLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании:.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По вопросам получения ключа лицензии обращайтесь в bimteam.org.
        /// </summary>
        public static string ForLicencePurchasingGoToBT {
            get {
                return ResourceManager.GetString("ForLicencePurchasingGoToBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратитесь в компанию bimteam для исправления ошибки.
        /// </summary>
        public static string GoToBTForFixError {
            get {
                return ResourceManager.GetString("GoToBTForFixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ключ.
        /// </summary>
        public static string IncorrectKey {
            get {
                return ResourceManager.GetString("IncorrectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ:.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия bimteam.
        /// </summary>
        public static string LicenceWindow {
            get {
                return ResourceManager.GetString("LicenceWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия активна.
        /// </summary>
        public static string LicenseValid {
            get {
                return ResourceManager.GetString("LicenseValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует подключение к интернету.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для дальнейшей работы bimteam panel необходимо подключение к интернету.
        ///Проверьте сетевое подключение или обратитесь к системному администратору..
        /// </summary>
        public static string NoInternetConnectionErrorText {
            get {
                return ResourceManager.GetString("NoInternetConnectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для корректной работы плагина рекомендуется перезапустить Revit.
        /// </summary>
        public static string RestartRevitForCorrectAddin {
            get {
                return ResourceManager.GetString("RestartRevitForCorrectAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка.
        /// </summary>
        public static string UnexpectedErrorHasOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorHasOccurred", resourceCulture);
            }
        }
    }
}
